package model;
import java.math.BigDecimal; import java.sql.Timestamp;
public class RefundRequest extends BaseEntity {
 private String refundCode,reason,refundMethod,bankName,bankAccountNumber,bankAccountName,status,rejectionReason; private long bookingId,customerId; private Long processedBy; private BigDecimal paidAmount,refundRate,refundAmount; private Timestamp requestedAt,processedAt,updatedAt;
 public String getRefundCode(){return refundCode;} public void setRefundCode(String v){refundCode=v;} public long getBookingId(){return bookingId;} public void setBookingId(long v){bookingId=v;} public long getCustomerId(){return customerId;} public void setCustomerId(long v){customerId=v;}
 public String getReason(){return reason;} public void setReason(String v){reason=v;} public String getRefundMethod(){return refundMethod;} public void setRefundMethod(String v){refundMethod=v;} public String getBankName(){return bankName;} public void setBankName(String v){bankName=v;} public String getBankAccountNumber(){return bankAccountNumber;} public void setBankAccountNumber(String v){bankAccountNumber=v;} public String getBankAccountName(){return bankAccountName;} public void setBankAccountName(String v){bankAccountName=v;}
 public BigDecimal getPaidAmount(){return paidAmount;} public void setPaidAmount(BigDecimal v){paidAmount=v;} public BigDecimal getRefundRate(){return refundRate;} public void setRefundRate(BigDecimal v){refundRate=v;} public BigDecimal getRefundAmount(){return refundAmount;} public void setRefundAmount(BigDecimal v){refundAmount=v;}
 public String getStatus(){return status;} public void setStatus(String v){status=v;} public String getRejectionReason(){return rejectionReason;} public void setRejectionReason(String v){rejectionReason=v;} public Timestamp getRequestedAt(){return requestedAt;} public void setRequestedAt(Timestamp v){requestedAt=v;} public Long getProcessedBy(){return processedBy;} public void setProcessedBy(Long v){processedBy=v;} public Timestamp getProcessedAt(){return processedAt;} public void setProcessedAt(Timestamp v){processedAt=v;} public Timestamp getUpdatedAt(){return updatedAt;} public void setUpdatedAt(Timestamp v){updatedAt=v;}
}
