/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.57
 * Generated at: 2026-08-13 17:44:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import model.Role;

public final class roles_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    private String h(Object value) {
        if (value == null) return "";
        return value.toString().replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace("\"", "&quot;").replace("'", "&#39;");
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.Role");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');

    List<Role> roles = (List<Role>) request.getAttribute("roles");
    Role editRole = (Role) request.getAttribute("editRole");
    boolean editing = editRole != null && editRole.getId() != null && editRole.getId() > 0;
    String action = editing ? "update" : "create";
    if (request.getAttribute("formAction") != null) action = request.getAttribute("formAction").toString();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"vi\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <title>Quản lý vai trò - HMS</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("<main id=\"main-content\" class=\"page-container\">\n");
      out.write("    <h1>Quản lý vai trò</h1>\n");
      out.write("\n");
      out.write("    ");
 if (request.getAttribute("error") != null) { 
      out.write("\n");
      out.write("        <div class=\"alert alert-error\">");
      out.print( h(request.getAttribute("error")) );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    ");
 if ("created".equals(request.getAttribute("success"))) { 
      out.write("\n");
      out.write("        <div class=\"alert alert-success\">Đã tạo vai trò.</div>\n");
      out.write("    ");
 } else if ("updated".equals(request.getAttribute("success"))) { 
      out.write("\n");
      out.write("        <div class=\"alert alert-success\">Đã cập nhật vai trò.</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <section class=\"panel\">\n");
      out.write("        <h2>");
      out.print( editing ? "Cập nhật vai trò" : "Tạo vai trò" );
      out.write("</h2>\n");
      out.write("        <form class=\"form-grid\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/roles\">\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"");
      out.print( h(action) );
      out.write("\">\n");
      out.write("            ");
 if (editing || "update".equals(action)) { 
      out.write("\n");
      out.write("                <input type=\"hidden\" name=\"id\" value=\"");
      out.print( editRole == null || editRole.getId() == null ? 0 : editRole.getId() );
      out.write("\">\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            <label>Tên vai trò\n");
      out.write("                <input class=\"form-control\" name=\"name\" value=\"");
      out.print( h(editRole == null ? "" : editRole.getName()) );
      out.write("\" required maxlength=\"40\" placeholder=\"ADMIN\">\n");
      out.write("            </label>\n");
      out.write("            <label>Mô tả\n");
      out.write("                <input class=\"form-control\" name=\"description\" value=\"");
      out.print( h(editRole == null ? "" : editRole.getDescription()) );
      out.write("\" maxlength=\"255\">\n");
      out.write("            </label>\n");
      out.write("            <div class=\"form-actions\">\n");
      out.write("                <button class=\"button button-primary\" type=\"submit\">");
      out.print( editing ? "Lưu thay đổi" : "Tạo vai trò" );
      out.write("</button>\n");
      out.write("                ");
 if (editing) { 
      out.write("\n");
      out.write("                    <a class=\"button button-secondary\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/roles\">Hủy</a>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <section class=\"panel\">\n");
      out.write("        <h2>Danh sách vai trò</h2>\n");
      out.write("        <div class=\"table-wrap\">\n");
      out.write("            <table class=\"data-table\">\n");
      out.write("                <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th>ID</th>\n");
      out.write("                    <th>Tên</th>\n");
      out.write("                    <th>Mô tả</th>\n");
      out.write("                    <th></th>\n");
      out.write("                </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                ");
 if (roles == null || roles.isEmpty()) { 
      out.write("\n");
      out.write("                    <tr><td colspan=\"4\">Không có vai trò.</td></tr>\n");
      out.write("                ");
 } else for (Role role : roles) { 
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>");
      out.print( role.getId() );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( h(role.getName()) );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( h(role.getDescription()) );
      out.write("</td>\n");
      out.write("                        <td><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/roles?edit=");
      out.print( role.getId() );
      out.write("\">Sửa</a></td>\n");
      out.write("                    </tr>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("</main>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
