/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.57
 * Generated at: 2026-08-13 17:44:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import model.User;
import model.Role;

public final class users_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    private String h(Object value) {
        if (value == null) return "";
        return value.toString().replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace("\"", "&quot;").replace("'", "&#39;");
    }

    private boolean selected(Object a, Object b) {
        return a != null && b != null && a.toString().equalsIgnoreCase(b.toString());
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("model.Role");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

    List<User> users = (List<User>) request.getAttribute("users");
    List<Role> roles = (List<Role>) request.getAttribute("roles");
    User editUser = (User) request.getAttribute("editUser");
    boolean editing = editUser != null && editUser.getUserId() > 0;
    String action = editing ? "update" : "create";
    if (request.getAttribute("formAction") != null) action = request.getAttribute("formAction").toString();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"vi\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <title>Quản lý người dùng - HMS</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("<main id=\"main-content\" class=\"page-container\">\n");
      out.write("    <h1>Quản lý người dùng</h1>\n");
      out.write("\n");
      out.write("    ");
 if (request.getAttribute("error") != null) { 
      out.write("\n");
      out.write("        <div class=\"alert alert-error\">");
      out.print( h(request.getAttribute("error")) );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    ");
 if ("created".equals(request.getAttribute("success"))) { 
      out.write("\n");
      out.write("        <div class=\"alert alert-success\">Đã tạo người dùng.</div>\n");
      out.write("    ");
 } else if ("updated".equals(request.getAttribute("success"))) { 
      out.write("\n");
      out.write("        <div class=\"alert alert-success\">Đã cập nhật người dùng.</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <section class=\"panel\">\n");
      out.write("        <h2>");
      out.print( editing ? "Cập nhật người dùng" : "Tạo người dùng" );
      out.write("</h2>\n");
      out.write("        <form class=\"form-grid\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/users\">\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"");
      out.print( h(action) );
      out.write("\">\n");
      out.write("            ");
 if (editing || "update".equals(action)) { 
      out.write("\n");
      out.write("                <input type=\"hidden\" name=\"id\" value=\"");
      out.print( editUser == null ? 0 : editUser.getUserId() );
      out.write("\">\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <label>Họ tên\n");
      out.write("                <input class=\"form-control\" name=\"fullName\" value=\"");
      out.print( h(editUser == null ? "" : editUser.getFullName()) );
      out.write("\" required maxlength=\"100\">\n");
      out.write("            </label>\n");
      out.write("\n");
      out.write("            <label>Email\n");
      out.write("                <input class=\"form-control\" type=\"email\" name=\"email\" value=\"");
      out.print( h(editUser == null ? "" : editUser.getEmail()) );
      out.write('"');
      out.write(' ');
      out.print( editing ? "readonly" : "required" );
      out.write(">\n");
      out.write("            </label>\n");
      out.write("\n");
      out.write("            ");
 if (!editing && !"update".equals(action)) { 
      out.write("\n");
      out.write("                <label>Mật khẩu\n");
      out.write("                    <input class=\"form-control\" type=\"password\" name=\"password\" minlength=\"8\" required>\n");
      out.write("                </label>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <label>Số điện thoại\n");
      out.write("                <input class=\"form-control\" name=\"phone\" value=\"");
      out.print( h(editUser == null ? "" : editUser.getPhone()) );
      out.write("\" maxlength=\"20\">\n");
      out.write("            </label>\n");
      out.write("\n");
      out.write("            <label>Vai trò\n");
      out.write("                <select class=\"form-control\" name=\"roleId\" required>\n");
      out.write("                    <option value=\"\">Chọn vai trò</option>\n");
      out.write("                    ");
 if (roles != null) for (Role role : roles) { 
      out.write("\n");
      out.write("                        <option value=\"");
      out.print( role.getId() );
      out.write('"');
      out.write(' ');
      out.print( editUser != null && editUser.getRoleId() == role.getId() ? "selected" : "" );
      out.write('>');
      out.print( h(role.getName()) );
      out.write("</option>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </select>\n");
      out.write("            </label>\n");
      out.write("\n");
      out.write("            <label>Trạng thái\n");
      out.write("                <select class=\"form-control\" name=\"status\" required>\n");
      out.write("                    ");
 String status = editUser == null || editUser.getStatus() == null ? "ACTIVE" : editUser.getStatus(); 
      out.write("\n");
      out.write("                    <option value=\"ACTIVE\" ");
      out.print( selected(status, "ACTIVE") ? "selected" : "" );
      out.write(">ACTIVE</option>\n");
      out.write("                    <option value=\"INACTIVE\" ");
      out.print( selected(status, "INACTIVE") ? "selected" : "" );
      out.write(">INACTIVE</option>\n");
      out.write("                    <option value=\"LOCKED\" ");
      out.print( selected(status, "LOCKED") ? "selected" : "" );
      out.write(">LOCKED</option>\n");
      out.write("                </select>\n");
      out.write("            </label>\n");
      out.write("\n");
      out.write("            <div class=\"form-actions\">\n");
      out.write("                <button class=\"button button-primary\" type=\"submit\">");
      out.print( editing ? "Lưu thay đổi" : "Tạo người dùng" );
      out.write("</button>\n");
      out.write("                ");
 if (editing) { 
      out.write("\n");
      out.write("                    <a class=\"button button-secondary\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/users\">Hủy</a>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <section class=\"panel\">\n");
      out.write("        <div class=\"section-header\">\n");
      out.write("            <h2>Danh sách người dùng</h2>\n");
      out.write("            <form class=\"search-form\" method=\"get\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/users\">\n");
      out.write("                <input class=\"form-control\" name=\"q\" value=\"");
      out.print( h(request.getParameter("q")) );
      out.write("\" placeholder=\"Tìm theo tên hoặc email\">\n");
      out.write("                <button class=\"button button-secondary\" type=\"submit\">Tìm</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"table-wrap\">\n");
      out.write("            <table class=\"data-table\">\n");
      out.write("                <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th>ID</th>\n");
      out.write("                    <th>Họ tên</th>\n");
      out.write("                    <th>Email</th>\n");
      out.write("                    <th>Điện thoại</th>\n");
      out.write("                    <th>Vai trò</th>\n");
      out.write("                    <th>Trạng thái</th>\n");
      out.write("                    <th></th>\n");
      out.write("                </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                ");
 if (users == null || users.isEmpty()) { 
      out.write("\n");
      out.write("                    <tr><td colspan=\"7\">Không có người dùng.</td></tr>\n");
      out.write("                ");
 } else for (User user : users) { 
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>");
      out.print( user.getUserId() );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( h(user.getFullName()) );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( h(user.getEmail()) );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( h(user.getPhone()) );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( h(user.getRoleName()) );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( h(user.getStatus()) );
      out.write("</td>\n");
      out.write("                        <td><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/users?edit=");
      out.print( user.getUserId() );
      out.write("\">Sửa</a></td>\n");
      out.write("                    </tr>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("</main>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
