/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.57
 * Generated at: 2026-08-12 17:23:11 UTC
 * Generated at: 2026-08-12 17:04:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.User;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    private String escapeHtml(String value) {
        if (value == null) return "";
        return value.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace("\"", "&quot;").replace("'", "&#39;");
    }

    private String roleLabel(int roleId) {
        switch (roleId) {
            case 1: return "Lễ tân";
            case 2: return "Buồng phòng";
            case 3: return "Kỹ thuật viên";
            case 4: return "Quản lý khách sạn";
            case 5: return "Quản trị hệ thống";
            default: return "Khách hàng";
        }
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    User headerUser = (User) session.getAttribute("currentUser");
    String contextPath = request.getContextPath();
    int roleId = headerUser == null ? -1 : headerUser.getRoleId();

      out.write("\n");
      out.write("<header class=\"site-header\">\n");
      out.write("    <div class=\"header-container\">\n");
      out.write("        <a class=\"brand\" href=\"");
      out.print( contextPath );
      out.write("/\" aria-label=\"Trang chủ HMS\">\n");
      out.write("            <span class=\"brand-mark\" aria-hidden=\"true\">H</span>\n");
      out.write("            <span class=\"brand-copy\"><strong>HMS</strong><small>Hotel Management System</small></span>\n");
      out.write("        </a>\n");
      out.write("\n");
      out.write("        <button class=\"nav-toggle\" type=\"button\" aria-expanded=\"false\"\n");
      out.write("                aria-controls=\"main-navigation\" aria-label=\"Mở menu\">☰</button>\n");
      out.write("\n");
      out.write("        <nav id=\"main-navigation\" class=\"main-nav\" aria-label=\"Điều hướng chính\">\n");
      out.write("            <a href=\"");
      out.print( contextPath );
      out.write("/\">Trang chủ</a>\n");
      out.write("\n");
      out.write("            ");
 if (headerUser == null || roleId == 0) { 
      out.write("\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/search\">Tìm phòng</a>\n");
      out.write("                ");
 if (headerUser != null) { 
      out.write("\n");
      out.write("                    <a href=\"");
      out.print( contextPath );
      out.write("/my-bookings\">Đặt phòng của tôi</a>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            ");
 if (roleId == 1) { 
      out.write("\n");
      out.write("                <div class=\"nav-dropdown\">\n");
      out.write("                    <button type=\"button\" class=\"dropdown-toggle\">Đặt phòng <span>▾</span></button>\n");
      out.write("                    <div class=\"dropdown-menu\">\n");
      out.write("                        <a href=\"");
      out.print( contextPath );
      out.write("/reception/bookings\">Danh sách đặt phòng</a>\n");
      out.write("                        <a href=\"");
      out.print( contextPath );
      out.write("/reception/walk-in\">Đặt phòng tại quầy</a>\n");
      out.write("                        <a href=\"");
      out.print( contextPath );
      out.write("/reception/room-map\">Sơ đồ phòng</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/reception/check-in\">Nhận phòng</a>\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/reception/check-out\">Trả phòng</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            ");
 if (roleId == 2) { 
      out.write("\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/housekeeping/tasks\">Công việc buồng phòng</a>\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/housekeeping/issues\">Báo cáo sự cố</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            ");
 if (roleId == 3) { 
      out.write("\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/technician/equipment\">Thiết bị</a>\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/technician/maintenance\">Bảo trì</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            ");
 if (roleId == 4) { 
      out.write("\n");
      out.write("                <div class=\"nav-dropdown\">\n");
      out.write("                    <button type=\"button\" class=\"dropdown-toggle\">Vận hành <span>▾</span></button>\n");
      out.write("                    <div class=\"dropdown-menu\">\n");
      out.write("                        <a href=\"");
      out.print( contextPath );
      out.write("/manager/room-types\">Phòng và loại phòng</a>\n");
      out.write("                        <a href=\"");
      out.print( contextPath );
      out.write("/manager/pricing\">Giá và dịch vụ</a>\n");
      out.write("                        <a href=\"");
      out.print( contextPath );
      out.write("/manager/staff\">Quản lý nhân viên</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/manager/reports\">Báo cáo thống kê</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            ");
 if (roleId == 5) { 
      out.write("\n");
      out.write("                <div class=\"nav-dropdown\">\n");
      out.write("                    <button type=\"button\" class=\"dropdown-toggle\">Quản trị <span>▾</span></button>\n");
      out.write("                    <div class=\"dropdown-menu\">\n");
      out.write("                        <a href=\"");
      out.print( contextPath );
      out.write("/admin/users\">Người dùng</a>\n");
      out.write("                        <a href=\"");
      out.print( contextPath );
      out.write("/admin/roles\">Vai trò và quyền</a>\n");
      out.write("                        <a href=\"");
      out.print( contextPath );
      out.write("/admin/system-config\">Cấu hình hệ thống</a>\n");
      out.write("                        <a href=\"");
      out.print( contextPath );
      out.write("/admin/backup\">Sao lưu</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/admin/logs\">Nhật ký hệ thống</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            ");
 if (headerUser == null) { 
      out.write("\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/login\">Đăng nhập</a>\n");
      out.write("                <a class=\"nav-primary\" href=\"");
      out.print( contextPath );
      out.write("/register\">Đăng ký</a>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <a class=\"user-chip\" href=\"");
      out.print( contextPath );
      out.write("/profile\" title=\"Xem hồ sơ\">\n");
      out.write("                    <span class=\"user-avatar\" aria-hidden=\"true\">●</span>\n");
      out.write("                    <span><strong>");
      out.print( escapeHtml(headerUser.getFullName()) );
      out.write("</strong>\n");
      out.write("                        <small>");
      out.print( roleLabel(roleId) );
      out.write("</small></span>\n");
      out.write("                </a>\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/change-password\">Đổi mật khẩu</a>\n");
      out.write("                <form class=\"logout-form\" method=\"post\" action=\"");
      out.print( contextPath );
      out.write("/logout\">\n");
      out.write("                    <button type=\"submit\">Đăng xuất</button>\n");
      out.write("                </form>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </nav>\n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write("<script>\n");
      out.write("    (() => {\n");
      out.write("        const header = document.currentScript.previousElementSibling;\n");
      out.write("        const toggle = header.querySelector('.nav-toggle');\n");
      out.write("        const nav = header.querySelector('.main-nav');\n");
      out.write("        toggle.addEventListener('click', () => {\n");
      out.write("            const open = nav.classList.toggle('is-open');\n");
      out.write("            toggle.setAttribute('aria-expanded', String(open));\n");
      out.write("            toggle.setAttribute('aria-label', open ? 'Đóng menu' : 'Mở menu');\n");
      out.write("        });\n");
      out.write("        header.querySelectorAll('.dropdown-toggle').forEach(button => {\n");
      out.write("            button.addEventListener('click', event => {\n");
      out.write("                event.stopPropagation();\n");
      out.write("                button.parentElement.classList.toggle('is-open');\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("        document.addEventListener('click', () => {\n");
      out.write("            header.querySelectorAll('.nav-dropdown.is-open').forEach(item => item.classList.remove('is-open'));\n");
      out.write("        });\n");
      out.write("    })();\n");
      out.write("</script>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
