/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.57
 * Generated at: 2026-08-12 16:22:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.User;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    private String escapeHtml(String value) {
        if (value == null) return "";
        return value.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

    User headerUser = (User) session.getAttribute("currentUser");
    String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<header class=\"site-header\">\r\n");
      out.write("    <div class=\"header-container\">\r\n");
      out.write("        <a class=\"brand\" href=\"");
      out.print( contextPath );
      out.write("/\" aria-label=\"Trang chủ HMS\">\r\n");
      out.write("            <span class=\"brand-mark\" aria-hidden=\"true\">H</span>\r\n");
      out.write("            <span class=\"brand-copy\">\r\n");
      out.write("                <strong>HMS</strong>\r\n");
      out.write("                <small>Hotel Management</small>\r\n");
      out.write("            </span>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"nav-toggle\" type=\"button\" aria-expanded=\"false\"\r\n");
      out.write("                aria-controls=\"main-navigation\" aria-label=\"Mở menu\">☰</button>\r\n");
      out.write("\r\n");
      out.write("        <nav id=\"main-navigation\" class=\"main-nav\" aria-label=\"Điều hướng chính\">\r\n");
      out.write("            <a href=\"");
      out.print( contextPath );
      out.write("/\">Trang chủ</a>\r\n");
      out.write("            ");
 if (headerUser == null) { 
      out.write("\r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/login\">Đăng nhập</a>\r\n");
      out.write("                <a class=\"nav-primary\" href=\"");
      out.print( contextPath );
      out.write("/register\">Đăng ký</a>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <span class=\"user-chip\" title=\"Tài khoản đang đăng nhập\">\r\n");
      out.write("                    <span class=\"user-avatar\" aria-hidden=\"true\">●</span>\r\n");
      out.write("                    <span>\r\n");
      out.write("                        <strong>");
      out.print( escapeHtml(headerUser.getFullName()) );
      out.write("</strong>\r\n");
      out.write("                        <small>");
      out.print( headerUser.getRoleId() == 0 ? "Khách hàng" : "Nhân viên" );
      out.write("</small>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </span>\r\n");
      out.write("                <form class=\"logout-form\" method=\"post\" action=\"");
      out.print( contextPath );
      out.write("/logout\">\r\n");
      out.write("                    <button type=\"submit\">Đăng xuất</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<script>\r\n");
      out.write("    (() => {\r\n");
      out.write("        const header = document.currentScript.previousElementSibling;\r\n");
      out.write("        const toggle = header.querySelector('.nav-toggle');\r\n");
      out.write("        const nav = header.querySelector('.main-nav');\r\n");
      out.write("        toggle.addEventListener('click', () => {\r\n");
      out.write("            const open = nav.classList.toggle('is-open');\r\n");
      out.write("            toggle.setAttribute('aria-expanded', String(open));\r\n");
      out.write("            toggle.setAttribute('aria-label', open ? 'Đóng menu' : 'Mở menu');\r\n");
      out.write("        });\r\n");
      out.write("    })();\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
