/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.57
 * Generated at: 2026-08-12 17:23:11 UTC
 * Generated at: 2026-08-12 17:04:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.public_;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Đăng nhập | HMS</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * { box-sizing: border-box; }\r\n");
      out.write("        body { margin: 0; min-height: 100vh; background: #f3f6fb; color: #172033; }\r\n");
      out.write("        .auth-content { min-height: calc(100vh - 71px); display: grid; place-items: center; padding: 24px; }\r\n");
      out.write("        .card { width: min(100%, 420px); background: #fff; border-radius: 16px; padding: 32px;\r\n");
      out.write("            box-shadow: 0 16px 45px rgba(20, 38, 70, .12); }\r\n");
      out.write("        h1 { margin: 0 0 8px; font-size: 28px; }\r\n");
      out.write("        .subtitle { margin: 0 0 24px; color: #687386; }\r\n");
      out.write("        label { display: block; margin: 16px 0 7px; font-weight: 600; }\r\n");
      out.write("        input { width: 100%; padding: 12px 14px; border: 1px solid #ccd3df; border-radius: 9px; font-size: 16px; }\r\n");
      out.write("        input:focus { outline: 3px solid #dce8ff; border-color: #316bd6; }\n");
      out.write("        .password-field { position: relative; }\n");
      out.write("        .password-field input { padding-right: 76px; }\n");
      out.write("        .password-toggle { position: absolute; right: 7px; top: 50%; transform: translateY(-50%); width: auto;\n");
      out.write("            margin: 0; padding: 7px 9px; background: transparent; color: #245ec7; font-size: 13px; }\n");
      out.write("        .password-toggle:hover { background: #edf4ff; }\n");
      out.write("        button { width: 100%; margin-top: 24px; padding: 13px; border: 0; border-radius: 9px;\n");
      out.write("            background: #245ec7; color: #fff; font-size: 16px; font-weight: 700; cursor: pointer; }\r\n");
      out.write("        button:hover { background: #194da9; }\r\n");
      out.write("        .secondary-action { display: block; margin-top: 10px; padding: 11px; border: 1px solid #ccd3df;\n");
      out.write("            border-radius: 9px; color: #245ec7; font-weight: 700; text-align: center; text-decoration: none; }\n");
      out.write("        .secondary-action:hover { background: #edf4ff; }\n");
      out.write("        .message { padding: 11px 13px; margin-bottom: 16px; border-radius: 8px; }\r\n");
      out.write("        .error { background: #fff0f0; color: #a51d27; }\r\n");
      out.write("        .success { background: #eaf8ef; color: #176438; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"auth-content\">\r\n");
      out.write("<main class=\"card\">\r\n");
      out.write("    <h1>Đăng nhập HMS</h1>\r\n");
      out.write("    <p class=\"subtitle\">Nhập tài khoản của bạn để tiếp tục.</p>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("        <div class=\"message error\" role=\"alert\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    ");
 if (request.getParameter("logout") != null) { 
      out.write("\n");
      out.write("        <div class=\"message success\" role=\"status\">Bạn đã đăng xuất thành công.</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    ");
 if (request.getParameter("reset") != null) { 
      out.write("\n");
      out.write("        <div class=\"message success\" role=\"status\">Đặt lại mật khẩu thành công. Bạn có thể đăng nhập.</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\r\n");
      out.write("    <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">\r\n");
      out.write("        <label for=\"email\">Email</label>\r\n");
      out.write("        <input id=\"email\" name=\"email\" type=\"email\" autocomplete=\"username\" required autofocus>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"password\">Mật khẩu</label>\n");
      out.write("        <div class=\"password-field\">\n");
      out.write("            <input id=\"password\" name=\"password\" type=\"password\" autocomplete=\"current-password\" required>\n");
      out.write("            <button class=\"password-toggle\" type=\"button\" data-password-toggle=\"password\">Hiện</button>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <button type=\"submit\">Đăng nhập</button>\n");
      out.write("    </form>\n");
      out.write("    <a class=\"secondary-action\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/forgot-password\">Quên mật khẩu?</a>\n");
      out.write("    <a class=\"secondary-action\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\">Tạo tài khoản mới</a>\n");
      out.write("</main>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("    document.querySelectorAll('[data-password-toggle]').forEach(button => {\n");
      out.write("        button.addEventListener('click', () => {\n");
      out.write("            const input = document.getElementById(button.dataset.passwordToggle);\n");
      out.write("            const showing = input.type === 'text';\n");
      out.write("            input.type = showing ? 'password' : 'text';\n");
      out.write("            button.textContent = showing ? 'Hiện' : 'Ẩn';\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
