/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.57
 * Generated at: 2026-08-16 14:41:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.public_;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    private String escapeAttr(Object value) {
        if (value == null) return "";
        return value.toString()
                .replace("&", "&amp;")
                .replace("\"", "&quot;")
                .replace("<", "&lt;")
                .replace(">", "&gt;");
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"vi\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <title>Đăng ký | HMS</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/auth.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("<main id=\"main-content\" class=\"auth-split-page register-page\">\n");
      out.write("    <section class=\"auth-hero\" aria-label=\"Giới thiệu HMS\">\n");
      out.write("        <div class=\"auth-hero-content\">\n");
      out.write("            <a class=\"auth-hero-logo\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">HMS</a>\n");
      out.write("            <p class=\"auth-hero-tagline\">Hotel Management System</p>\n");
      out.write("            <div class=\"auth-preview-card auth-preview-main\">\n");
      out.write("                <span class=\"auth-preview-title\">Theo dõi đặt phòng</span>\n");
      out.write("                <div class=\"auth-preview-stats\">\n");
      out.write("                    <span><strong>3</strong>Bước</span>\n");
      out.write("                    <span><strong>24/7</strong>Hỗ trợ</span>\n");
      out.write("                    <span><strong>1</strong>Tài khoản</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"auth-preview-card auth-preview-phone\">\n");
      out.write("                <span class=\"auth-preview-dot\"></span>\n");
      out.write("                <span class=\"auth-preview-line\"></span>\n");
      out.write("                <span class=\"auth-preview-line short\"></span>\n");
      out.write("                <span class=\"auth-preview-button\"></span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <section class=\"auth-panel\" aria-labelledby=\"auth-title\">\n");
      out.write("        <div class=\"auth-card auth-card-register\">\n");
      out.write("        <a class=\"auth-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">HMS</a>\n");
      out.write("        <p class=\"auth-subtitle\">Hệ thống quản lý khách sạn</p>\n");
      out.write("        <h1 id=\"auth-title\">Đăng ký</h1>\n");
      out.write("        <p class=\"auth-form-note\">Tạo tài khoản để theo dõi và quản lý đặt phòng.</p>\n");
      out.write("        ");
 if (request.getAttribute("error") != null) { 
      out.write("\n");
      out.write("            <div class=\"auth-message error\" role=\"alert\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <form class=\"auth-form\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\">\n");
      out.write("            <div class=\"auth-field\">\n");
      out.write("                <label for=\"fullName\">Họ và tên</label>\n");
      out.write("                <input id=\"fullName\" name=\"fullName\" maxlength=\"100\" autocomplete=\"name\" value=\"");
      out.print( escapeAttr(request.getAttribute("fullName")) );
      out.write("\" required autofocus>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"auth-field\">\n");
      out.write("                <label for=\"email\">Email</label>\n");
      out.write("                <input id=\"email\" name=\"email\" type=\"email\" maxlength=\"150\" autocomplete=\"email\" value=\"");
      out.print( escapeAttr(request.getAttribute("email")) );
      out.write("\" required>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"auth-field\">\n");
      out.write("                <label for=\"phone\">Số điện thoại</label>\n");
      out.write("                <input id=\"phone\" name=\"phone\" type=\"tel\" maxlength=\"20\" autocomplete=\"tel\" value=\"");
      out.print( escapeAttr(request.getAttribute("phone")) );
      out.write("\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"auth-field\">\n");
      out.write("                <label for=\"password\">Mật khẩu</label>\n");
      out.write("                <div class=\"password-wrap\">\n");
      out.write("                    <input id=\"password\" name=\"password\" type=\"password\" minlength=\"8\" maxlength=\"255\"\n");
      out.write("                           autocomplete=\"new-password\" required>\n");
      out.write("                    <button class=\"password-visibility\" type=\"button\" data-toggle-password=\"password\"\n");
      out.write("                            aria-label=\"Hiện mật khẩu\">Hiện</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"auth-field\">\n");
      out.write("                <label for=\"confirmPassword\">Xác nhận mật khẩu</label>\n");
      out.write("                <div class=\"password-wrap\">\n");
      out.write("                    <input id=\"confirmPassword\" name=\"confirmPassword\" type=\"password\" minlength=\"8\" maxlength=\"255\"\n");
      out.write("                           autocomplete=\"new-password\" required>\n");
      out.write("                    <button class=\"password-visibility\" type=\"button\" data-toggle-password=\"confirmPassword\"\n");
      out.write("                            aria-label=\"Hiện mật khẩu xác nhận\">Hiện</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <button class=\"auth-submit\" type=\"submit\" data-loading-label=\"Đang tạo tài khoản...\">Đăng ký</button>\n");
      out.write("        </form>\n");
      out.write("        <p class=\"auth-switch\">Đã có tài khoản? <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">Đăng nhập</a></p>\n");
      out.write("        <a class=\"auth-guest\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search\">Tiếp tục với tư cách khách</a>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("</main>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/auth.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
