<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.util.List" %>
<%@ page import="model.AuditLog" %>
<%!
    private String h(Object value) {
        if (value == null) return "";
        return String.valueOf(value).replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace("\"", "&quot;").replace("'", "&#39;");
    }
%>
<%
    List<AuditLog> logs = (List<AuditLog>) request.getAttribute("logs");
    String q = (String) request.getAttribute("q");
    int limit = request.getAttribute("limit") == null ? 100 : (Integer) request.getAttribute("limit");
%>
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>System Logs - HMS</title>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/main.css?v=20260816-4">
    <style>
        .admin-tabs { display:flex; gap:10px; margin-bottom:20px; border-bottom:1px solid var(--color-border); padding-bottom:10px; }
        .admin-tabs a { padding:8px 14px; border-radius:6px; text-decoration:none; font-weight:700; color:#344054; }
        .admin-tabs a.active { background:var(--color-primary-100); color:var(--color-primary-600); }
        .filters { display:flex; gap:10px; flex-wrap:wrap; align-items:end; margin-bottom:16px; }
        .data-table { width:100%; border-collapse:collapse; background:#fff; border:1px solid var(--color-border); border-radius:8px; overflow:hidden; }
        .data-table th,.data-table td { padding:11px 12px; border-bottom:1px solid var(--color-border); text-align:left; vertical-align:top; }
        .data-table th { background:var(--color-bg-surface); color:var(--color-text-secondary); font-size:13px; }
        .code { font-family:Consolas, monospace; font-size:12px; }
        .message { margin-bottom:14px; padding:10px 12px; border-radius:8px; border:1px solid #fecaca; background:#fef2f2; color:#991b1b; }
    </style>
</head>
<body>
<jsp:include page="/WEB-INF/views/common/header.jsp" />
<main class="page-container">
    <nav class="admin-tabs">
        <a href="${pageContext.request.contextPath}/admin/users">Users</a>
        <a href="${pageContext.request.contextPath}/admin/roles">Roles & Permissions</a>
        <a class="active" href="${pageContext.request.contextPath}/admin/logs">System Logs</a>
    </nav>

    <h1>System Logs Viewer</h1>
    <p>View system log entries generated by administration actions.</p>

    <% if (request.getAttribute("error") != null) { %>
        <div class="message"><%= h(request.getAttribute("error")) %></div>
    <% } %>

    <form class="filters" method="get" action="${pageContext.request.contextPath}/admin/logs">
        <div>
            <label class="form-label" for="q">Search</label>
            <input class="form-control" id="q" name="q" value="<%= h(q) %>" placeholder="Action, actor, target, detail">
        </div>
        <div>
            <label class="form-label" for="limit">Limit</label>
            <select class="form-control" id="limit" name="limit">
                <option value="50" <%= limit == 50 ? "selected" : "" %>>50</option>
                <option value="100" <%= limit == 100 ? "selected" : "" %>>100</option>
                <option value="250" <%= limit == 250 ? "selected" : "" %>>250</option>
                <option value="500" <%= limit == 500 ? "selected" : "" %>>500</option>
            </select>
        </div>
        <button class="button button-secondary" type="submit">Filter</button>
    </form>

    <table class="data-table">
        <thead>
        <tr><th>Time</th><th>Actor</th><th>Action</th><th>Target</th><th>IP</th><th>Detail</th></tr>
        </thead>
        <tbody>
        <% if (logs != null && !logs.isEmpty()) for (AuditLog log : logs) { %>
            <tr>
                <td><%= h(log.getCreatedAt()) %></td>
                <td><%= h(log.getActorName() == null ? log.getActorId() : log.getActorName()) %></td>
                <td class="code"><%= h(log.getAction()) %></td>
                <td><%= h(log.getTargetType()) %> #<%= h(log.getTargetId()) %></td>
                <td class="code"><%= h(log.getIpAddress()) %></td>
                <td><%= h(log.getDetail()) %></td>
            </tr>
        <% } else { %>
            <tr><td colspan="6">No log entries found.</td></tr>
        <% } %>
        </tbody>
    </table>
</main>
</body>
</html>
