<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.util.List" %>
<%@ page import="java.net.URLEncoder" %>
<%@ page import="java.nio.charset.StandardCharsets" %>
<%@ page import="model.AuditLog" %>
<%!
    private String h(Object value) {
        if (value == null) return "";
        return String.valueOf(value).replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace("\"", "&quot;").replace("'", "&#39;");
    }
    private String enc(Object value) {
        if (value == null) return "";
        return URLEncoder.encode(String.valueOf(value), StandardCharsets.UTF_8);
    }
%>
<%
    List<AuditLog> logs = (List<AuditLog>) request.getAttribute("logs");
    String q = (String) request.getAttribute("q");
    int limit = request.getAttribute("limit") == null ? 5 : (Integer) request.getAttribute("limit");
    int currentPage = request.getAttribute("page") == null ? 1 : (Integer) request.getAttribute("page");
    int totalPages = request.getAttribute("totalPages") == null ? 1 : (Integer) request.getAttribute("totalPages");
    int totalItems = request.getAttribute("totalItems") == null ? 0 : (Integer) request.getAttribute("totalItems");
    String pageQuery = "&q=" + enc(q);
%>
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>System Logs - HMS</title>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/main.css?v=20260816-4">
    <style>
        .admin-tabs { display:flex; gap:10px; margin-bottom:20px; border-bottom:1px solid var(--color-border); padding-bottom:10px; }
        .admin-tabs a { padding:8px 14px; border-radius:6px; text-decoration:none; font-weight:700; color:#344054; }
        .admin-tabs a.active { background:var(--color-primary-100); color:var(--color-primary-600); }
        .filters { display:flex; gap:10px; flex-wrap:wrap; align-items:end; margin-bottom:16px; }
        .data-table { width:100%; border-collapse:collapse; background:#fff; border:1px solid var(--color-border); border-radius:8px; overflow:hidden; }
        .data-table th,.data-table td { padding:11px 12px; border-bottom:1px solid var(--color-border); text-align:left; vertical-align:top; }
        .data-table th { background:var(--color-bg-surface); color:var(--color-text-secondary); font-size:13px; }
        .code { font-family:Consolas, monospace; font-size:12px; }
        .message { margin-bottom:14px; padding:10px 12px; border-radius:8px; border:1px solid #fecaca; background:#fef2f2; color:#991b1b; }
        .pagination-bar { display:flex; justify-content:space-between; align-items:center; gap:12px; flex-wrap:wrap; margin-top:14px; }
        .pagination-links { display:flex; gap:6px; align-items:center; flex-wrap:wrap; }
        .page-link { min-width:38px; min-height:36px; display:inline-flex; align-items:center; justify-content:center; padding:7px 11px; border:1px solid var(--color-border); border-radius:8px; background:#fff; color:var(--color-text-primary); font-weight:700; text-decoration:none; }
        .page-link.active { border-color:var(--color-primary-600); background:var(--color-primary-600); color:#fff; }
        .page-link.disabled { opacity:.45; pointer-events:none; }
    </style>
</head>
<body>
<jsp:include page="/WEB-INF/views/common/header.jsp" />
<main class="page-container">
    <nav class="admin-tabs">
        <a href="${pageContext.request.contextPath}/admin/users">Users</a>
        <a href="${pageContext.request.contextPath}/admin/roles">Roles & Permissions</a>
        <a class="active" href="${pageContext.request.contextPath}/admin/logs">System Logs</a>
    </nav>

    <h1>System Logs Viewer</h1>
    <p>View system log entries generated by administration actions.</p>

    <% if (request.getAttribute("error") != null) { %>
        <div class="message"><%= h(request.getAttribute("error")) %></div>
    <% } %>

    <form class="filters" method="get" action="${pageContext.request.contextPath}/admin/logs">
        <div>
            <label class="form-label" for="q">Search</label>
            <input class="form-control" id="q" name="q" value="<%= h(q) %>" placeholder="Action, actor, target, detail">
        </div>
        <button class="button button-secondary" type="submit">Filter</button>
    </form>

    <table class="data-table">
        <thead>
        <tr><th>Time</th><th>Actor</th><th>Action</th><th>Target</th><th>IP</th><th>Detail</th></tr>
        </thead>
        <tbody>
        <% if (logs != null && !logs.isEmpty()) for (AuditLog log : logs) { %>
            <tr>
                <td><%= h(log.getCreatedAt()) %></td>
                <td><%= h(log.getActorName() == null ? log.getActorId() : log.getActorName()) %></td>
                <td class="code"><%= h(log.getAction()) %></td>
                <td><%= h(log.getTargetType()) %> #<%= h(log.getTargetId()) %></td>
                <td class="code"><%= h(log.getIpAddress()) %></td>
                <td><%= h(log.getDetail()) %></td>
            </tr>
        <% } else { %>
            <tr><td colspan="6">No log entries found.</td></tr>
        <% } %>
        </tbody>
    </table>
    <div class="pagination-bar">
        <span>Showing <%= logs == null ? 0 : logs.size() %> of <%= totalItems %> log entries, 5 per page</span>
        <div class="pagination-links">
            <a class="page-link <%= currentPage <= 1 ? "disabled" : "" %>" href="${pageContext.request.contextPath}/admin/logs?page=<%= currentPage - 1 %><%= pageQuery %>">Prev</a>
            <% for (int i = 1; i <= totalPages; i++) {
                if (i == 1 || i == totalPages || Math.abs(i - currentPage) <= 2) { %>
                    <a class="page-link <%= i == currentPage ? "active" : "" %>" href="${pageContext.request.contextPath}/admin/logs?page=<%= i %><%= pageQuery %>"><%= i %></a>
                <% } else if (i == currentPage - 3 || i == currentPage + 3) { %>
                    <span class="page-link disabled">...</span>
                <% }
            } %>
            <a class="page-link <%= currentPage >= totalPages ? "disabled" : "" %>" href="${pageContext.request.contextPath}/admin/logs?page=<%= currentPage + 1 %><%= pageQuery %>">Next</a>
        </div>
    </div>
</main>
</body>
</html>
